# LoreRuneTerra ? Configuración de base de datos
# IMPORTANTE: este archivo NO debe subirse a GitHub (.gitignore)
db.host=localhost
db.port=5432
db.name=loreruneterra
db.user=postgres
db.password=0031
